### PR TITLE
Navbar and Landing components are now responsive, Navbar placed in the layout.jsx, some small changes

### PR DESCRIPTION
**Pull request by Naveed-SNR**

### CODE REVIEW

**Review by devdaim6 — CHANGES_REQUESTED** [review]
Hamburger Menu styling needs to be fixed

**Comment by Naveed-SNR** [comment]
> Hamburger Menu styling needs to be fixed

Check now, I had added h-screen class by mistake.

**Comment by Naveed-SNR** [comment]
@devdaim6 Don't merge yet I noticed a minor issue on medium-sized screens. Let me fix that first.

**Comment by devdaim6** [comment]
> > Hamburger Menu styling needs to be fixed
> 
> Check now, I had added h-screen class by mistake.

Screenshot_2024-07-20-09-26-58-67
Screenshot_2024-07-20-09-26-54-19

same issue plus bachround color also removed

**Comment by Naveed-SNR** [comment]
> > > Hamburger Menu styling needs to be fixed
> > 
> > 
> > Check now, I had added h-screen class by mistake.
> 
> Screenshot_2024-07-20-09-26-58-67 Screenshot_2024-07-20-09-26-54-19
> 
> same issue plus bachround color also removed

I remember adding h-screen because bg-color wasn't showing. I didn't touch any other styles for the sidebar. I added h-screen again and bg-color is showing and it doesn't overflow either. I don't what was causing the overflow before but there is no overflow now even though all the styles for the sidebar are the same.

**Comment by devdaim6** [comment]
> > > > Hamburger Menu styling needs to be fixed
> > > 
> > > 
> > > Check now, I had added h-screen class by mistake.
> > 
> > 
> > Screenshot_2024-07-20-09-26-58-67 Screenshot_2024-07-20-09-26-54-19
> > same issue plus bachround color also removed
> 
> I remember adding h-screen because bg-color wasn't showing. I didn't touch any other styles for the sidebar. I added h-screen again and bg-color is showing and it doesn't overflow either. I don't what was causing the overflow before but there is no overflow now even though all the styles for the sidebar are the same.

check for ambiguity of classes

**Comment by Naveed-SNR** [comment]
> > > > > Hamburger Menu styling needs to be fixed
> > > > 
> > > > 
> > > > Check now, I had added h-screen class by mistake.
> > > 
> > > 
> > > Screenshot_2024-07-20-09-26-58-67 Screenshot_2024-07-20-09-26-54-19
> > > same issue plus bachround color also removed
> > 
> > 
> > I remember adding h-screen because bg-color wasn't showing. I didn't touch any other styles for the sidebar. I added h-screen again and bg-color is showing and it doesn't overflow either. I don't what was causing the overflow before but there is no overflow now even though all the styles for the sidebar are the same.
> 
> check for ambiguity of classes

I reverted to the original styles pushed by Ikhlas, the overflow issue is still there, seems like the changes I made had nothing to with the issue. I'll try fixing it.

**Comment by devdaim6** [comment]
> > > > > > Hamburger Menu styling needs to be fixed
> > > > > 
> > > > > 
> > > > > Check now, I had added h-screen class by mistake.
> > > > 
> > > > 
> > > > Screenshot_2024-07-20-09-26-58-67 Screenshot_2024-07-20-09-26-54-19
> > > > same issue plus bachround color also removed
> > > 
> > > 
> > > I remember adding h-screen because bg-color wasn't showing. I didn't touch any other styles for the sidebar. I added h-screen again and bg-color is showing and it doesn't overflow either. I don't what was causing the overflow before but there is no overflow now even though all the styles for the sidebar are the same.
> > 
> > 
> > check for ambiguity of classes
> 
> I reverted to the original styles pushed by Ikhlas, the overflow issue is still there, seems like the changes I made had nothing to with the issue. I'll try fixing it.

Might be problem in Header Component @Naveed-SNR

**Comment by devdaim6** [comment]
Screenshot_2024-07-20-10-02-58-27

i pulled lstest commit from ikhlas but it doesnt have any issues

**Review by devdaim6 — APPROVED** [review]
Screenshot_2024-07-20-11-46-15-99

Links kaerzi update

**Pull request merged**
